const gigActions = {
    CHANGE_INPUT: "CHANGE_INPUT",
    ADD_IMAGES: "ADD_IMAGES",
    REMOVE_IMAGES: "REMOVE_IMAGES",
    ADD_FEATURES: "ADD_FEATURES",
    REMOVE_FEATURES : "REMOVE_FEATURES"
}

export default gigActions;